### FC tools

[[tools]]
name = "betaflight-configurator"
url = "https://github.com/betaflight/betaflight-configurator"
tag = "10.7.2"
desktop_name = "Betaflight Configurator"
comment = "Configure Betaflight flight controllers"
icon = "bf_icon_128.png"

[[tools]]
name = "blackbox-log-viewer"
url = "https://github.com/betaflight/blackbox-log-viewer"
tag = "3.5.0"
desktop_name = "Blackbox Log Viewer"
comment = "View blackbox logs"
icon = "bf_icon_128.png"

[[tools]]
name = "inav-configurator"
url = "https://github.com/iNavFlight/inav-configurator"
tag = "4.0.0"
desktop_name = "INAV Configurator"
comment = "Configure INAV flight controllers"
icon = "inav_icon_128.png"

### ESC tools

[[tools]]
name = "blheli-configurator"
url = "https://github.com/blheli-configurator/blheli-configurator"
tag = "1.2.0"
desktop_name = "BLHeli Configurator"
comment = "Configure & flash BLHeli und BLHeli_s ESCs"
icon = "icon_128.png"

[[tools]]
name = "blheli_m-configurator"
url = "https://github.com/Asizon/blheli-configurator"
tag = "1.2.0-jazzmaverick-beta4"
desktop_name = "BLHeli_m Configurator"
comment = "Configure and Flash SiLabs ESCs with the JazzMaverick firmware"
icon = "icon_128.png"

[[tools]]
name = "jesc-configurator"
url = "https://github.com/jflight-public/jesc-configurator/"
tag = "v1.2.10b1"
desktop_name = "JESC Configurator"
comment = "Configure and Flash SiLabs ESCs with the JESC firmware"
icon = "icon_128.png"
